
import 'categoryselection.dart';
import 'product.dart';

class AppData {
  static List<Product> momentList = [
    Product(
        id:1,
        name: 'Nike Air Max 200',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/baby1.jpg',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        isSelected: true,
        image: 'assets/baby2.jpg',
        category: "Trending Now"),
    Product(
        id:1,
        name: 'Nike Air Max 200',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/baby3.jpg',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        isSelected: true,
        image: 'assets/baby4.jpg',
        category: "Trending Now"),
    Product(
        id:1,
        name: 'Rebook Air 200',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/baby5.jpg',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Rebook Air 99',
        price: 220.00,
        isliked: false,
        isSelected: true,
        image: 'assets/baby12.jpg',
        category: "Trending Now"),
    Product(
        id:1,
        name: 'Rebook Air 250',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/baby13.jpg',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Rebook Air Max 97',
        price: 220.00,
        isliked: false,
        isSelected: true,
        image: 'assets/baby14.jpg',
        category: "Trending Now"),
    Product(
        id:1,
        name: 'Nike Air Max 200',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/baby15.jpg',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        isSelected: true,
        image: 'assets/baby16.jpg',
        category: "Trending Now"),
    Product(
        id:1,
        name: 'Nike Air Max 200',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/baby21.jpg',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        isSelected: true,
        image: 'assets/baby22.jpg',
        category: "Trending Now"),
    Product(
        id:1,
        name: 'Rebook Air 200',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/baby23.jpg',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Rebook Air 99',
        price: 220.00,
        isliked: false,
        isSelected: true,
        image: 'assets/baby24.jpg',
        category: "Trending Now"),
    Product(
        id:1,
        name: 'Rebook Air 250',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/baby25.jpg',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Rebook Air Max 97',
        price: 220.00,
        isliked: false,
        isSelected: true,
        image: 'assets/baby26.jpg',
        category: "Trending Now"),
  ];


  static List<Product> productTrendingList = [
    Product(
        id:1,
        name: 'Nike Air Max 200',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/small_tilt_shoe_2.png',
        category: "Trending Now"),
    Product(
        id:2,
        name: 'Nike Air Max 97',
        price: 190.00,
        isliked: false,
        image: 'assets/small_tilt_shoe_2.png',
        category: "Trending Now"),
    Product(
        id:1,
        name: 'Nike Air Max 92607',
        price: 220.00,
        isliked: false,
        image: 'assets/small_tilt_shoe_3.png',
        category: "Trending Now"),
     Product(
        id:2,
        name: 'Nike Air Max 200',
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: 'assets/small_tilt_shoe_1.png',
        category: "Trending Now"),
  ];

  static List<Product> clothesList = [
    Product(
        id:1,
        name:  "Yellow shot frock",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: "assets/clothes1.jpg",
        category: "Trending Now"),
    Product(
        id:2,
        name: "Summer clothes",
        price: 190.00,
        isliked: false,
        image:  "assets/clothes2.jpg",
        category: "Trending Now"),
    Product(
        id:1,
        name:  "newborn baby",
        price: 220.00,
        isliked: false,
        image: "assets/clothes3.jpg",
        category: "Trending Now"),
    Product(
        id:2,
        name: "Filar top",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image:  "assets/clothes4.jpg",
        category: "Trending Now"),
     Product(
         id:1,
         name: "jeans with Top",
         price: 190.00,
         isliked: false,
         image: "assets/clothes5.jpg",
           category: "Trending Now"),
    Product(
        id:1,
        name: "Black t-shirt",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: "assets/clothes6.jpg",
        category: "Trending Now"),
    Product(
        id:2,
        name: "Fairy frook",
        price: 190.00,
        isliked: false,
        image:  "assets/clothes7.jpg",
        category: "Trending Now"),
    Product(
        id:1,
        name: "Night Dress",
        price: 220.00,
        isliked: false,
        image: "assets/clothes8.jpg",
        category: "Trending Now"),
    Product(
        id:2,
        name:  "White dotted top",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image:  "assets/clothes9.jpg",
        category: "Trending Now"),
    Product(
        id:1,
        name:  "one Foundation",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: "assets/clothes8.jpg",
        category: "Trending Now"),

  ];

  static List<Product> jacketList = [
    Product(
        id:1,
        name:  "light pink jacket",
        price: 2400.00,
        isSelected: true,
        isliked: false,
        image:  "assets/jacket.jpg",
        category: "Trending Now"),
    Product(
        id:2,
        name:  "black wool jacket",
        price: 1900.00,
        isliked: false,
        image:   "assets/jackets1.jpg",
        category: "Trending Now"),
    Product(
        id:1,
        name:  "pink leather jacket",
        price: 2200.00,
        isliked: false,
        image:  "assets/jackets2.jpg",
        category: "Trending Now"),
    Product(
        id:2,
        name: "denim x1 jacket",
        price: 2400.00,
        isSelected: true,
        isliked: false,
        image:   "assets/jackets3.jpg",
        category: "Trending Now"),
    Product(
        id:1,
        name: "denium xx1 jacket",
        price: 1900.00,
        isliked: false,
        image:  "assets/jackets4.jpg",
        category: "Trending Now"),
    Product(
        id:1,
        name: "air proof jacket",
        price: 2400.00,
        isSelected: true,
        isliked: false,
        image:  "assets/jackets5.jpg",
        category: "Trending Now"),
    Product(
        id:2,
        name: "x2 white jacket",
        price: 1900.00,
        isliked: false,
        image:   "assets/jackets6.jpg",
        category: "Trending Now"),
    Product(
        id:1,
        name: "leather jacket",
        price: 2200.00,
        isliked: false,
        image:  "assets/jackets7.jpg",
        category: "Trending Now"),
    Product(
        id:2,
        name: "short  jacket",
        price: 2400.00,
        isSelected: true,
        isliked: false,
        image:   "assets/jackets8.jpg",
        category: "Trending Now"),
    Product(
        id:1,
        name: "black x3 jacket",
        price: 2400.00,
        isSelected: true,
        isliked: false,
        image:  "assets/jackets9.jpg",
        category: "Trending Now"),

  ];
  static List<Product> watchList = [
    Product(
        id:1,
        name: "white dial watch",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: "assets/watch1.jfif",
        category: "Trending Now"),
    Product(
        id:2,
        name: "Redux anlog dial",
        price: 190.00,
        isliked: false,
        image:  "assets/watch2.jfif",
        category: "Trending Now"),
    Product(
        id:1,
        name: "Fogg-116 brown",
        price: 220.00,
        isliked: false,
        image: "assets/watch3.jfif",
        category: "Trending Now"),
    Product(
        id:2,
        name: "Denialkelin watch",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image:  "assets/watch4.jfif",
        category: "Trending Now"),
    Product(
        id:1,
        name: "By redux x2 ",
        price: 190.00,
        isliked: false,
        image: "assets/watch5.jfif",
        category: "Trending Now"),
    Product(
        id:1,
        name:  "Diwti 001 watch",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: "assets/watch6.jfif",
        category: "Trending Now"),
    Product(
        id:2,
        name: "Risto-9434",
        price: 190.00,
        isliked: false,
        image:  "assets/watch7.jfif",
        category: "Trending Now"),
    Product(
        id:1,
        name: "Fastrack",
        price: 220.00,
        isliked: false,
        image:  "assets/watch8.jfif",
        category: "Trending Now"),
    Product(
        id:2,
        name: "Titan",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image:  "assets/watch9.jfif",
        category: "Trending Now"),
    Product(
        id:1,
        name: "G-shock",
        price: 240.00,
        isSelected: true,
        isliked: false,
        image: "assets/watch10.jfif",
        category: "Trending Now"),
    ];
  static List<Category> categoryList = [
    Category(),
    Category(id:1,name: "Sneakers",image: 'assets/shoe_thumb_2.png',),
    Category(id:2,name: "Jacket", image: 'assets/jacket.png'),
    Category(id:3,name: "Watch", image: 'assets/watch.png'),
    Category(id:4,name: "fashion", image: 'assets/watch.png'),
  ];
  static List<String> showThumbnailList = [
    "assets/shoe_thumb_5.png",
    "assets/shoe_thumb_1.png",
    "assets/shoe_thumb_4.png",
    "assets/shoe_thumb_3.png",
  ];
  static List<String> listOfLikes = [
    "240",
    "190",
    "200",
    "240",
    "190",
    "220 ",
    "240",
    "240",
    "190",
    "432",
    "190",
    "200",
    "190",






  ];
  static String description = "Clean lines, versatile and timeless—the people shoe returns with the Nike Air Max 90. Featuring the same iconic Waffle sole, stitched overlays and classic TPU accents you come to love, it lets you walk among the pantheon of Air. ßNothing as fly, nothing as comfortable, nothing as proven. The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle sole, stitched overlays and classic TPU details. Classic colours celebrate your fresh look while Max Air cushioning adds comfort to the journey.";
}
